name: expansions
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - cffi=1.15.1
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.6
  - expat=2.2.10
  - faiss-gpu=1.7.3
  - ffmpeg=4.3
  - freetype=2.12.1
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - icu=67.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - jinja2=3.1.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libfaiss=1.7.3
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - lz4-c=1.9.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - mscorefonts=0.0.1
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjdk=11.0.13
  - openssl=1.1.1l
  - pcre=8.45
  - pillow=9.4.0
  - pip=23.0.1
  - pycparser=2.21
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytorch=2.0.1
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - readline=8.2
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - tornado=6.1
  - typing_extensions=4.5.0
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - absl-py==2.0.0
      - accelerate==0.24.1
      - aiohttp==3.8.4
      - aiosignal==1.3.1
      - anthropic==0.2.10
      - antlr4-python3-runtime==4.8
      - anyio==3.7.1
      - async-timeout==4.0.2
      - attrs==23.1.0
ug      - beautifulsoup4==4.12.2
      - beir==2.0.0
      - bitarray==2.8.1
      - bitsandbytes==0.39.0
      - blinker==1.6.2
      - blis==0.7.9
      - catalogue==2.0.8
      - cbor==1.0.0
      - chardet==5.1.0
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cmake==3.26.3
      - coloredlogs==15.0.1
      - confection==0.0.4
      - contourpy==1.1.0
      - cymem==2.0.7
      - cython==0.29.35
      - data==0.4
      - dataclasses-json==0.5.8
      - datasets==2.12.0
      - decorator==5.1.1
      - dill==0.3.6
      - distro==1.8.0
      - docker==6.1.3
      - elasticsearch==7.9.1
      - emoji==2.4.0
      - evaluate==0.4.0
      - exceptiongroup==1.1.3
      - faiss-cpu==1.7.4
      - filelock==3.12.0
      - flask==2.3.2
      - flatbuffers==23.5.26
      - fonttools==4.42.0
      - frozenlist==1.3.3
      - fsspec==2023.5.0
      - ftfy==6.1.1
      - funcsigs==1.0.2
      - future==0.18.3
      - gdown==4.7.1
      - git-python==1.0.3
      - gitdb==4.0.10
      - gitpython==3.1.32
      - greenlet==2.0.2
      - h11==0.14.0
      - httpcore==0.17.3
      - httpx==0.24.1
      - huggingface-hub==0.15.1
      - humanfriendly==10.0
      - ijson==3.2.0.post0
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.1
      - ir-datasets==0.5.4
      - itsdangerous==2.1.2
      - joblib==1.2.0
      - langchain==0.0.205
      - langchainplus-sdk==0.0.13
      - langcodes==3.3.0
      - latex==0.7.0
      - lightgbm==3.3.5
      - lit==16.0.5
      - lxml==4.9.2
      - lz4==4.3.2
      - markdown-it-py==3.0.0
      - markupsafe==2.1.2
      - marshmallow==3.19.0
      - marshmallow-enum==1.5.1
      - matplotlib==3.7.1
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - murmurhash==1.0.9
      - mypy-extensions==1.0.0
      - networkx==3.1
      - ninja==1.11.1
      - nltk==3.8.1
      - nmslib==2.1.1
      - numexpr==2.8.4
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - omegaconf==2.1.2
      - onnxruntime==1.15.0
      - openai==0.27.8
      - openapi-schema-pydantic==1.2.4
      - packaging==23.1
      - pandas==2.0.2
      - pathy==0.10.1
      - peft==0.6.0
      - preshed==3.0.8
      - protobuf==4.23.2
      - psutil==5.9.5
      - pyarrow==12.0.0
      - pyautocorpus==0.1.9
      - pybind11==2.6.1
      - pydantic==1.10.8
      - pygments==2.15.1
      - pyjnius==1.5.0
      - pyparsing==3.0.9
      - pyserini==0.21.0
      - python-dotenv==1.0.0
      - pytrec-eval==0.5
      - pytz==2023.3
      - pyyaml==6.0
      - regex==2023.5.5
      - requests==2.31.0
      - responses==0.18.0
      - rich==13.4.2
      - rouge-score==0.1.2
      - sacremoses==0.0.53
      - safetensors==0.3.3
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - seaborn==0.12.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - shutilwhich==1.1.0
      - sklearn==0.0.post5
      - smart-open==6.3.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - spacy==3.5.3
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.4
      - sqlalchemy==2.0.16
      - srsly==2.4.6
      - sseclient-py==1.7.2
      - stanza==1.5.0
      - sympy==1.12
      - tempdir==0.7.1
      - tenacity==8.2.2
      - thinc==8.1.10
      - threadpoolctl==3.1.0
      - tiktoken==0.4.0
      - together==0.1.9
      - tokenizers==0.13.3
      - torch==2.0.0
      - tqdm==4.66.1
      - transformers==4.32.1
      - trec-car-tools==2.6
      - triton==2.0.0
      - typer==0.7.0
      - typing-extensions==4.6.2
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - ujson==5.8.0
      - unlzw3==0.2.2
      - urllib3==2.0.2
      - warc3-wet==0.2.3
      - warc3-wet-clueweb09==0.2.5
      - wasabi==1.1.1
      - wcwidth==0.2.6
      - websocket-client==1.5.3
      - werkzeug==2.3.6
      - xxhash==3.2.0
      - yarl==1.9.2
      - zipp==3.16.2
      - zlib-state==0.1.5
